/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LogIns;

/**
 *
 * @author Denver Makama
 */
public class Receptionist extends javax.swing.JFrame {

    /**
     * Creates new form Receptionist
     */
    public Receptionist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtnPatients = new javax.swing.JButton();
        jbtnDoctors = new javax.swing.JButton();
        jbtnPersonalDetails = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Rceptionist's Portal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 476, 74));

        jbtnPatients.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnPatients.setText("Patients Form");
        jbtnPatients.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPatientsActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPatients, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 376, -1, -1));

        jbtnDoctors.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnDoctors.setText("Doctors' Portal");
        jbtnDoctors.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDoctorsActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDoctors, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 376, -1, -1));

        jbtnPersonalDetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnPersonalDetails.setText("Personal Details");
        jbtnPersonalDetails.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnPersonalDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPersonalDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPersonalDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 376, -1, -1));

        jbtnBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnBack.setText("Back");
        jbtnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 170, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPatientsActionPerformed
        Patients obj=new Patients();
        obj.setVisible(true);
    }//GEN-LAST:event_jbtnPatientsActionPerformed

    private void jbtnDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDoctorsActionPerformed
       Doctors obj=new Doctors();
        obj.setVisible(true);
    }//GEN-LAST:event_jbtnDoctorsActionPerformed

    private void jbtnPersonalDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPersonalDetailsActionPerformed
        Receptionist_PersonalInfo obj = new Receptionist_PersonalInfo ();
        obj.setVisible(true);
    }//GEN-LAST:event_jbtnPersonalDetailsActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        LogIn_Portal obj = new LogIn_Portal ();
        obj.setVisible(true);
    }//GEN-LAST:event_jbtnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receptionist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnDoctors;
    private javax.swing.JButton jbtnPatients;
    private javax.swing.JButton jbtnPersonalDetails;
    // End of variables declaration//GEN-END:variables
}
